# From https://github.com/hvr/multi-ghc-travis

# NB: don't set `language: haskell` here
# language: haskell

# Use Travis CI's docker based install
# We can't use sudo in the docker environment
# See - http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
    - env: GHCVER=7.8.3 STACK_YAML=stack-7.8.yaml
      addons: {apt: {sources: [hvr-ghc], packages: [ghc-7.8.3]}}
    - env: GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml
      addons: {apt: {sources: [hvr-ghc], packages: [ghc-7.8.4]}}
    - env: GHCVER=7.10.1 STACK_YAML=stack-7.10.yaml
      addons: {apt: {sources: [hvr-ghc], packages: [ghc-7.10.1]}}
  allow_failures:
    - env: GHCVER=head STACK_YAML=stack-head.yaml
      addons: {apt: {sources: [hvr-ghc], packages: [ghc-head]}}

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - mkdir -p ~/.local/bin
 - export PATH=~/.local/bin:$PATH
 - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz | gunzip > ~/.local/bin/stack
 - chmod a+x ~/.local/bin/stack
 - uname -a
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - ghc --info
 - stack +RTS -N1 -RTS --version

install:
 - stack +RTS -N1 -RTS --no-terminal --skip-ghc-check setup
 - stack +RTS -N1 -RTS --no-terminal --skip-ghc-check build --only-snapshot
 - stack +RTS -N1 -RTS --no-terminal --skip-ghc-check test --only-snapshot

script:
 - stack +RTS -N1 -RTS --no-terminal --skip-ghc-check build
 - stack +RTS -N1 -RTS --no-terminal --skip-ghc-check test

after_script:
  - cat dist/test/*.log
  # Coverage analysis with coverall.io
  - stack install hpc-coveralls
  - hpc-coveralls simple

